name: streamlit_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn=1.0.2
  - numpy=1.26.4
  - pip
  - pip:
      - streamlit==1.24.1
      - requests==2.32.3
      - pandas==2.3.0
      
